version: '3.7'
services:
  fit-db:
    image: postgres:15.1-bullseye
    ports:
      - 5432:5432
    networks:
      - fit-net
    environment:
      POSTGRES_PASSWORD: fit123!
      POSTGRES_DB: fit
      POSTGRES_USER: fit
    volumes:
      - fit-db:/var/lib/postgresql/data      
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
  fit-files:
    image:  minio/minio:RELEASE.2023-01-25T00-19-54Z
    environment: 
      MINIO_ROOT_USER: s3fit
      MINIO_ROOT_PASSWORD: s3fit123!
      # MINIO_REGION: "eu-west-2" -- not working with .net client
    command: server /storage --console-address ":9090"      
    ports:
      - 9000:9000
      - 9090:9090        
    volumes:
      - fit-files:/storage
    networks:
      - fit-net          
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M      
networks:
  fit-net:
volumes:
  fit-db:
  fit-files:
